package com.pace.honda.pacehonda;

/**
 * Created by ashutoshkumarojha on 07/12/17.
 */

public class StaticValus {

    public static String aboutUs="<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><strong><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-variant-ligatures: normal; font-variant-caps: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Pioneer Group &ndash; About Us</span></strong></p>\n"+
            "<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">The project is promoted by Pioneer Cars (India ) Pvt Ltd, a private limited company incorporated under the Companies Act, 1956, having its registered office at Kannothumchal, Kannur. Incepted in 1981, We at PIONEER GROUP take pride in presenting ourselves as renowned Dealers and Service, of major players of 2, 3 and 4 wheelers in the Indian Market. </span></p>\n"+
            "<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">We are working with a team of customer friendly manufacturers and suppliers and supported by a dexterous team of talented customer friendly sales and service team. Our strong infrastructure assists us in executing business and service of any size while adhering to quality standards and client specifications. Every stage of service process is closely monitored by our dedicated supervisors to ensure smooth flow of standard process. Over the years, our service have gained immense recognition and appreciation from manufacturers and suppliers for our excellent performance. </span></p>\n"+
            "<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Our excellent facilities allow us to provide our clients with high quality relationship. We also use latest technology to facilitate service standards in accordance with the client's requirement. They work in close proximity with the clients to comprehend their requirements and working according to those. Moreover, our units are designed and maintained as per the industrial standards. Our service specifications allows us to keep a check on all stages of service to ensure optimum utilization of resources. Directors The project is promoted by Pioneer Cars (India ) Pvt Ltd, a private limited company incorporated under the Companies Act, 1956, having its Registered Office at Kannothumchal in Kannur. </span></p>\n"+
            "<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Sri. Rajan Pothan and Sri. Sureshan Pothan of Pioneer Group of companies are the directors of the company. The brief profiles of the directors are as follows. Rajan Pothan :- Sri.Rajan Pothan is a dynamic businessman hailing from Kannur having more than 30 years experience in automobile industry. After completion of his Diploma in Automobile Engineering from HIET, Chennai, he ventured to set up M/s.Pioneer Auto Engineering Works, a Maruthi Authorized Service Station at Kannur in 1981. He expanded to automobile dealership in 1993 by establishing Pioneer Motors(Kannur) Pvt Ltd at Kannothumchal in Kannur to take up the dealership of Yamaha Two Wheelers , Piaggio Vehicles and Honda Two Wheelers in Kannur District. </span></p>\n"+
            "<p style=\"line-height: 1.3800000000000001; margin-top: 0pt; margin-bottom: 10pt;\"><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #333333; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">This was followed by establishment of Pothan &amp; Pothan Automobiles Pvt Ltd in 1997 for Yamaha Two Wheeler dealership in Kannur and distributor for Greaves Cotton Ltd for their light engine spares for seven districts in Northern Kerala. Both Pioneer Motors (Kannur) Pvt Ltd and Pothan &amp; Pothan Automobiles Pvt Ltd have gone on to become the leading dealerships in the district. Besides the above concerns, Sri .Rajan Pothan has also promoted Pioneer motors for Yamaha two wheelers and Pace Motors for Honda two wheelers in kasaragod district in the year 2000 and 2006 respectively. His latest venture is Wayanad Vehicles Pvt Ltd in Kalpetta which is the authorized dealers for Piaggio Vehicles in Wayanad District. He has served as a catalyst to the growth and prosperity of Pioneer Group by providing guidance and direction to the group's operations. He is instrumental in making the Pioneer Group one of the leading business houses in North Kerala.</span></p>";


    public static String address = "<div class=\"off_address col-md-12 col-sm-12 col-xs-12\">\n" +
            "                                                <h4>Honda Motorcycle &amp; Scooter India Pvt. Ltd.</h4>\n" +
            "                                                <p>\n" +
            "                                                    Commercial Complex II, Sector: 49-50<br>\n" +
            "                                                    Golf Course Extension Road,<br>                                                                                              Gurgaon, Haryana (122018) India\n" +
            "                                                </p>\n" +
            "                                                <p><i class=\"fa fa-phone\" aria-hidden=\"true\"></i> Phone: <a href=\"tel:+9101246712800\">+91(0)124-6712800</a></p>\n" +
            "                                                <p><i class=\"fa fa-fax\" aria-hidden=\"true\"></i> Fax: +91(0)124-6712999</p>\n" +
            "                                            </div>";

}
